var window = require('./base64');
var {mIndexedDB} = require('sdk/indexed-db');
var time = require('sdk/timers');


setTimeout = time.setTimeout;
clearTimeout = time.clearTimeout;
setInterval = time.setInterval;
clearInterval = time.clearInterval;

(function (name, definition, context) {if (typeof context['module'] !== 'undefined' && context['module']['exports']) {context['module']['exports'] = definition.apply(context);}else if (typeof context['define'] !== 'undefined' && context['define'] === 'function' && context['define']['amd']) {define(name, [], definition);}else {context[name] = definition();}})('ydn', function () {var m,q=this;
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function r(a){return void 0!==a}function s(a){return"array"==ba(a)}function t(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){return"string"==typeof a}function ca(a){return"boolean"==typeof a}function x(a){return"number"==typeof a}function da(a){return"function"==ba(a)}function y(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var ea="closure_uid_"+(1E9*Math.random()>>>0),fa=0;
function ga(a,b,c){return a.call.apply(a.bind,arguments)}function ha(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function z(a,b,c){z=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ga:ha;return z.apply(null,arguments)}
function ia(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var ja=Date.now||function(){return+new Date};function ka(a,b){var c=a.split("."),d=q;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b}
function A(a,b){function c(){}c.prototype=b.prototype;a.p=b.prototype;a.prototype=new c;a.Ma=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};function la(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0}function ma(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function B(a){if(Error.captureStackTrace)Error.captureStackTrace(this,B);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}A(B,Error);B.prototype.name="CustomError";function na(a){for(var b=0;1>b;b++)if('"'==a.charAt(0)&&'"'==a.charAt(a.length-1))return a.substring(1,a.length-1);return a}var pa={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"},qa={"'":"\\'"};
function ra(a){a=String(a);if(!a.quote){for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0),f=b,g=c+1,h;if(!(h=pa[d])){if(!(31<e&&127>e))if(d in qa)d=qa[d];else if(d in pa)d=qa[d]=pa[d];else{e=d;h=d.charCodeAt(0);if(31<h&&127>h)e=d;else{if(256>h){if(e="\\x",16>h||256<h)e+="0"}else e="\\u",4096>h&&(e+="0");e+=h.toString(16).toUpperCase()}d=qa[d]=e}h=d}f[g]=h}b.push('"')}};function sa(a){da(q.setImmediate)?q.setImmediate(a):(ta||(ta=ua()),ta(a))}var ta;
function ua(){if(q.fa&&q.fa.resolve){var a=q.fa.resolve();return function(b){a.then(b)}}var b=q.MessageChannel;"undefined"===typeof b&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(b=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d=b.location.protocol+"//"+b.location.host,a=z(function(a){if(a.origin==
d||a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof b){var c=new b,d={},e=d;c.port1.onmessage=function(){d=d.next;var a=d.ha;d.ha=null;a()};return function(a){e.next={ha:a};e=e.next;c.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=
null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){q.setTimeout(a,0)}};function va(a){sa(function(){throw a;})}function wa(a,b){xa||(sa(ya),xa=!0);za.push(new Aa(a,b))}var xa=!1,za=[];function ya(){for(;za.length;){var a=za;za=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){va(d)}}}xa=!1}function Aa(a,b){this.a=a;this.b=b};function Ba(a,b){this.b=Ca;this.f=void 0;this.a=this.c=null;this.d=this.e=!1;try{var c=this;a.call(b,function(a){Da(c,Ea,a)},function(a){Da(c,Fa,a)})}catch(d){Da(this,Fa,d)}}var Ca=0,Ea=2,Fa=3;Ba.prototype.then=function(a,b,c){return Ga(this,da(a)?a:null,da(b)?b:null,c)};la(Ba);function Ha(a){a.b==Ca&&wa(function(){var a=new Ia(void 0);Ja(this,a)},a)}
function Ja(a,b){if(a.b==Ca)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.O)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(c.b==Ca&&1==d?Ja(c,b):(d=c.a.splice(e,1)[0],Fa==Ea?d.$(b):(Ka(c),d.aa(b))))}}else Da(a,Fa,b)}function La(a,b){a.a&&a.a.length||a.b!=Ea&&a.b!=Fa||Ma(a);a.a||(a.a=[]);a.a.push(b)}
function Ga(a,b,c,d){var e={O:null,$:null,aa:null};e.O=new Ba(function(a,g){e.$=b?function(c){try{var e=b.call(d,c);a(e)}catch(p){g(p)}}:a;e.aa=c?function(b){try{var e=c.call(d,b);!r(e)&&b instanceof Ia?g(b):a(e)}catch(p){g(p)}}:g});e.O.c=a;La(a,e);return e.O}Ba.prototype.g=function(a){this.b=Ca;Da(this,Ea,a)};Ba.prototype.h=function(a){this.b=Ca;Da(this,Fa,a)};
function Da(a,b,c){if(a.b==Ca){if(a==c)b=Fa,c=new TypeError("Promise cannot resolve to itself");else{if(ma(c)){a.b=1;c.then(a.g,a.h,a);return}if(y(c))try{var d=c.then;if(da(d)){Na(a,c,d);return}}catch(e){b=Fa,c=e}}a.f=c;a.b=b;Ma(a);b!=Fa||c instanceof Ia||Oa(a,c)}}function Na(a,b,c){function d(b){f||(f=!0,a.h(b))}function e(b){f||(f=!0,a.g(b))}a.b=1;var f=!1;try{c.call(b,e,d)}catch(g){d(g)}}function Ma(a){a.e||(a.e=!0,wa(a.j,a))}
Ba.prototype.j=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++){var c=a[b],d=this.f;this.b==Ea?c.$(d):(Ka(this),c.aa(d))}}this.e=!1};function Ka(a){for(;a&&a.d;a=a.c)a.d=!1}function Oa(a,b){a.d=!0;wa(function(){a.d&&Pa.call(null,b)})}var Pa=va;function Ia(a){B.call(this,a)}A(Ia,B);Ia.prototype.name="cancel";var Qa=Array.prototype,Ra=Qa.indexOf?function(a,b,c){return Qa.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(u(a))return u(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Sa=Qa.map?function(a,b,c){return Qa.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=u(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},Ta=Qa.some?function(a,b,c){return Qa.some.call(a,b,c)}:function(a,b,c){for(var d=
a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};function Ua(a,b){var c;a:{c=a.length;for(var d=u(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:u(a)?a.charAt(c):a[c]}function Va(a){if(!s(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0}function Wa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function Xa(a,b){if(!t(a)||!t(b)||a.length!=b.length)return!1;for(var c=a.length,d=Ya,e=0;e<c;e++)if(!d(a[e],b[e]))return!1;return!0}function Ya(a,b){return a===b};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function E(a,b){this.h=[];this.F=b||null;this.b=this.c=!1;this.e=void 0;this.ja=this.B=this.j=!1;this.g=0;this.d=null;this.n=0}m=E.prototype;m.P=function(a,b){this.j=!1;Za(this,a,b)};function Za(a,b,c){a.c=!0;a.e=c;a.b=!b;a.X()}function $a(a){if(a.c){if(!a.ja)throw new ab;a.ja=!1}}m.k=function(a){$a(this);Za(this,!0,a)};m.i=function(a){$a(this);Za(this,!1,a)};m.s=function(a,b){return F(this,a,null,b)};m.ra=function(a,b){return F(this,null,a,b)};m.ga=function(a,b){return F(this,a,a,b)};
function F(a,b,c,d){a.h.push([b,c,d]);a.c&&a.X();return a}m.then=function(a,b,c){var d,e,f=new Ba(function(a,b){d=a;e=b});F(this,d,function(a){e(a)});return f.then(a,b,c)};la(E);E.prototype.Aa=function(a){var b=new E;F(this,b.k,b.i,b);a&&(b.d=this,this.n++);return b};function bb(a){return Ta(a.h,function(a){return da(a[1])})}
E.prototype.X=function(){this.g&&this.c&&bb(this)&&(cb(this.g),this.g=0);this.d&&(this.d.n--,delete this.d);for(var a=this.e,b=!1,c=!1;this.h.length&&!this.j;){var d=this.h.shift(),e=d[0],f=d[1],d=d[2];if(e=this.b?f:e)try{var g=e.call(d||this.F,a);r(g)&&(this.b=this.b&&(g==a||g instanceof Error),this.e=a=g);ma(a)&&(this.j=c=!0)}catch(h){a=h,this.b=!0,bb(this)||(b=!0)}}this.e=a;c&&(c=z(this.P,this,!0),g=z(this.P,this,!1),a instanceof E?(F(a,c,g),a.B=!0):a.then(c,g));b&&(a=new db(a),eb[a.S]=a,this.g=
a.S)};function ab(){B.call(this)}A(ab,B);ab.prototype.message="Deferred has already fired";ab.prototype.name="AlreadyCalledError";function db(a){this.S=q.setTimeout(z(this.b,this),0);this.a=a}db.prototype.b=function(){delete eb[this.S];throw this.a;};var eb={};function cb(a){var b=eb[a];b&&(q.clearTimeout(b.S),delete eb[a])};function G(a){B.call(this,a);this.name="ydn.error.ArgumentException"}A(G,B);function fb(a){B.call(this,a);this.name="ydn.error.NotSupportedException"}A(fb,B);function gb(a){B.call(this,a);this.name="ydn.error.InvalidOperationException"}A(gb,B);function hb(a){Error.captureStackTrace?Error.captureStackTrace(this,hb):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.error.InternalError"}A(hb,Error);hb.prototype.name="ydn.error.InternalError";function ib(a,b){for(var c=t(b),d=c?b:arguments,c=c?0:1;c<d.length&&(a=a[d[c]],r(a));c++);return a};var jb;a:{var kb=q.navigator;if(kb){var lb=kb.userAgent;if(lb){jb=lb;break a}}jb=""}function mb(a){return-1!=jb.indexOf(a)};var nb=mb("Opera")||mb("OPR"),ob=mb("Trident")||mb("MSIE"),pb=mb("Gecko")&&-1==jb.toLowerCase().indexOf("webkit")&&!(mb("Trident")||mb("MSIE")),qb=-1!=jb.toLowerCase().indexOf("webkit");(function(){var a="",b;if(nb&&q.opera)return a=q.opera.version,da(a)?a():a;pb?b=/rv\:([^\);]+)(\)|;)/:ob?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:qb&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(jb))?a[1]:"");return ob&&(b=(b=q.document)?b.documentMode:void 0,b>parseFloat(a))?String(b):a})();function rb(){};function sb(a,b){E.call(this,0,b);this.f=[]}A(sb,E);sb.prototype.za=function(a,b){this.f.push([a,b]);return this};sb.prototype.k=function(a){this.f.length=0;sb.p.k.call(this,a)};sb.prototype.i=function(a){this.f.length=0;sb.p.i.call(this,a)};var tb={READ_ONLY:"readonly",READ_WRITE:"readwrite",VERSION_CHANGE:"versionchange"},ub=q.IDBRequest&&"LOADING"in q.IDBRequest?q.IDBTransaction:q.webkitIDBRequest&&"LOADING"in q.webkitIDBRequest&&1===q.webkitIDBTransaction.READ_WRITE?q.webkitIDBTransaction:tb,H=ub.READ_ONLY,I=ub.READ_WRITE,vb=ub.VERSION_CHANGE,J=q.indexedDB||q.mozIndexedDB||q.webkitIndexedDB||q.moz_indexedDB||q.msIndexedDB;E.prototype.done=E.prototype.s;E.prototype.fail=E.prototype.ra;E.prototype.always=E.prototype.ga;sb.prototype.then=sb.prototype.then;function wb(a,b){var c,d;2==arguments.length&&u(arguments[1])?(c=!0,d=arguments[1].split(".")):d=(c=t(b))?b:arguments;for(c=c?0:1;c<d.length&&(a=a[d[c]],r(a));c++);return a}function xb(a,b,c){if(a)if(-1==b.indexOf("."))a[b]=c;else{b=b.split(".");for(var d=b.pop(),e;e=b.shift();)y(a[e])||(a[e]={}),a=a[e];a[d]=c}}var yb={};
function zb(a){var b=[a];a=new Ab;for(var c=0,d,e;void 0!==(e=b.pop());){0===c%4&&12<c+4&&(a.write(c),c=0);d=typeof e;if(e instanceof Array)if(c+=4,0<e.length){b.push(yb);for(d=e.length;d--;)b.push(e[d]);continue}else a.write(c);else if("number"===d)c+=1,a.write(c),Bb(a,e);else if(e instanceof Date)c+=2,a.write(c),Bb(a,e.valueOf());else if("string"===d){c+=3;a.write(c);c=a;for(d=0;d<e.length;d++){var f=e.charCodeAt(d);126>=f?c.write(f+1):16510>=f?(f-=127,c.write(128|f>>8,f&255)):c.write(192|f>>10,
f>>2|255,(f|3)<<6)}c.write(0)}else if(e===yb)a.write(0);else return"";c=0}for(b=a.a.length;"00"===a.a[--b];);a.a.length=++b;return a.toString()}
function Bb(a,b){var c,d,e;c=b;var f=e=d=0;if(0!==c)if(isFinite(c)){0>c&&(d=1,c=-c);f=0;if(2.2250738585072014E-308<=c){for(e=c;1>e;)f--,e*=2;for(;2<=e;)f++,e/=2;e=f+1023}f=e?Math.floor(4503599627370496*(c/Math.pow(2,f)-1)):Math.floor(c/4.9E-324)}else e=2047,isNaN(c)?f=0x8000000000000:-Infinity===c&&(d=1);c=d;d=e;e=f;c&&(e=0xfffffffffffff-e,d=2047-d);a.write((c?0:128)|d>>4);a.write((d&15)<<4|0|e/281474976710656);e%=281474976710656;c=0|e/4294967296;a.write(c>>8,c&255);e%=4294967296;c=0|e/65536;a.write(c>>
8,c&255);c=e%65536;a.write(c>>8,c&255)}function Ab(){this.a=[];this.b=void 0}Ab.prototype.write=function(a){for(var b=0;b<arguments.length;b++)this.b=arguments[b].toString(16),this.a.push(2===this.b.length?this.b:this.b="0"+this.b)};Ab.prototype.toString=function(){return this.a.length?this.a.join(""):""};function Cb(a,b){var c=zb(a),d=zb(b);return c>d?1:c==d?0:-1};function L(a,b,c){sb.call(this,0,c);this.q=a;this.f=[];this.m=[];this.la=[];this.a=null;this.K=""}A(L,sb);m=L.prototype;m.K="";function Db(a,b,c){a.a=b;a.K=c;if(b){for(c=0;c<a.m.length;c++)a.m[c][0].call(a.m[c][1],b);a.m.length=0}}m.sa=function(){return!!this.a};m.abort=function(){if(this.a)if(da(this.a.abort))this.a.abort();else if(da(this.a.executeSql))this.a.executeSql("ABORT",[],function(){},function(){return!0});else throw new fb;else throw new Eb("");};
function N(a,b,c){var d=a.la.shift();c=!!c;d?d[0].call(d[1],b,c,function(b,c){N(a,b,c)}):c?a.i(b):a.k(b)}function Fb(a,b,c){a.la.push([b,c])}function O(a,b,c){a.a?b.call(c,a.a):a.m.push([b,c])}m.k=function(a){L.p.k.call(this,a)};m.i=function(a){L.p.i.call(this,a)};function Gb(a){var b="";a.K&&(b=a.a?"*":"",b="["+a.K+b+"]");return a.q+b}function Hb(a,b){var c=new L(a);N(c,b);return c}m.Ia=function(){return this};m.toString=function(){return"Request:"+Gb(this)};
m.X=function(){this.g&&this.c&&bb(this)&&(cb(this.g),this.g=0);this.d&&(this.d.n--,delete this.d);for(var a=this.e,b=!1;this.h.length&&!this.j;){var c=this.h.shift(),d=c[0],e=c[1],c=c[2];if(d=this.b?e:d)d=d.call(c||this.F,a),r(d)&&(this.b=this.b&&(d==a||d instanceof Error),this.e=a=d),ma(a)&&(this.j=b=!0)}this.e=a;b&&(b=z(this.P,this,!0),d=z(this.P,this,!1),a instanceof E?(F(a,b,d),a.B=!0):a.then(b,d))};
m.toJSON=function(){var a=(this.K||"").match(/B(\d+)T(\d+)(?:Q(\d+?))?(?:R(\d+))?/)||[];return{method:this.q?this.q.split(":"):[],branchNo:parseFloat(a[1]),transactionNo:parseFloat(a[2]),queueNo:parseFloat(a[3]),requestNo:parseFloat(a[4])}};var Ib=J&&J.cmp?z(J.cmp,J):Cb,Jb=[];function Kb(){0!=Lb&&(this[ea]||(this[ea]=++fa))}var Lb=0;function Mb(a,b){this.type=a;this.target=b}Mb.prototype.preventDefault=function(){};function Nb(a,b){Mb.call(this,a,b)}A(Nb,Mb);Nb.prototype.a=function(){return this.b};function Ob(a,b,c,d,e){Mb.call(this,a,b);this.version=c;this.na=d;this.ka=e}A(Ob,Nb);m=Ob.prototype;m.name="ReadyEvent";m.version=NaN;m.na=NaN;m.ka=null;m.Ka=function(){return this.version};m.va=function(){return this.na};m.ua=function(){return this.ka};function Pb(a,b,c){Mb.call(this,c||"error",a);this.error=b}A(Pb,Nb);Pb.prototype.toString=function(){return this.name+":"+(this.error?this.error:"")};
Pb.prototype.name="ErrorEvent";Pb.prototype.error=null;Pb.prototype.c=function(){return this.error};function Qb(a,b){Pb.call(this,a,b,"fail")}A(Qb,Pb);Qb.prototype.name="FailEvent";function Q(a,b,c){var d;if(y(a))d=a.store,b=a.id,null!=a.parent&&(c=new Q(a.parent));else if(r(b))d=a;else if(d=a.lastIndexOf("^|"),b=a,0<d&&(b=a.substr(d),c=new Q(a.substring(0,d))),b=b.split("^:"),d=b[0],b=b[1],!r(b))throw Error("Invalid key value: "+a);this.a=d;this.b=b;this.c=c||null}m=Q.prototype;m.toJSON=function(){var a={store:this.a,id:this.b};this.c&&(a.parent=this.c.toJSON());return a};m.valueOf=function(){return(this.c?this.c.valueOf()+"^|":"")+this.a+"^:"+this.b};
m.toString=function(){return this.valueOf().replace("^|","|").replace("^:",":")};m.Ea=function(){return this.a};m.ta=function(){return this.b};m.Da=function(){return this.c};function Rb(a){if(t(a)){for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}return a};function R(a,b,c,d){this.lower=a;this.upper=b;this.lowerOpen=!!c;this.upperOpen=!!d}R.prototype.lower=void 0;R.prototype.upper=void 0;R.prototype.toJSON=function(){var a;a=this||{};return{lower:a.lower,upper:a.upper,lowerOpen:a.lowerOpen,upperOpen:a.upperOpen}};function Sb(a){return Tb(a)}R.only=function(a){return new R(a,a,!1,!1)};R.bound=function(a,b,c,d){return new R(a,b,c,d)};R.upperBound=function(a,b){return new R(void 0,a,void 0,!!b)};R.lowerBound=function(a,b){return new R(a,void 0,!!b,void 0)};
function Ub(a){var b;if(s(a))b=Wa(a),b.push("\uffff");else if(u(a))b=a+"\uffff";else if(x(a))b=a+2.220460492503131E-16,a-=2.220460492503131E-16;else return R.only(a);return R.bound(a,b,!1,!0)}function Tb(a){return null!=a?null!=a.upper&&null!=a.lower?Vb.bound(a.lower,a.upper,!!a.lowerOpen,!!a.upperOpen):null!=a.upper?Vb.upperBound(a.upper,a.upperOpen):null!=a.lower?Vb.lowerBound(a.lower,a.lowerOpen):null:null}
function Wb(a,b){var c=a.lower,d=a.upper,e=a.lowerOpen,f=a.upperOpen;null!=b.lower&&(null==a.lower||b.lower>=a.lower)&&(c=b.lower,e=b.lowerOpen||a.lowerOpen);null!=b.upper&&(null==a.upper||b.upper<=a.upper)&&(d=b.upper,f=b.upperOpen||a.upperOpen);return R.bound(c,d,e,f)}
function Xb(a,b,c,d){var e,f,g,h;if("starts"==a||"^"==a)return Ub(b);if("<"==a||"<="==a)e=b,g="<"==a;else if(">"==a||">="==a)f=b,h=">"==a;else if("="==a||"=="==a)e=f=b;else throw new G("invalid op: "+a);if("<"==c||"<="==c)e=d,g="<"==c;else if(">"==c||">="==c)f=d,h=">"==c;else if(r(c))throw new G("invalid op2: "+c);return R.bound(f,e,h,g)}var Vb=q.IDBKeyRange||q.webkitIDBKeyRange||R;function Yb(a,b,c,d,e,f){r(e)||(e=s(a)?a.join(", "):a);if(null!=a&&!u(a)&&!t(a))throw new G("index keyPath for "+e+" must be a string or array, but "+a+" is "+typeof a);!r(a)&&r(e)&&(a=e);this.keyPath=a;this.e=t(this.keyPath);this.a=e;this.type=Zb(b);if(r(b)){if(!r(this.type))throw new G("type invalid in index: "+this.a);if(s(this.keyPath))throw new G('composite key for store "'+this.a+'" must not specified type');}this.unique=!!c;this.multiEntry=!!d;this.d=u(e)?e:s(a)?this.keyPath.join(","):a;ra(this.d);
this.b=this.e?null:this.keyPath.split(".");this.c=f||null}var $b=["BLOB","DATE","INTEGER","NUMERIC","TEXT"];function Zb(a){if(u(a))return a=Ra($b,a),$b[a]}Yb.prototype.getName=function(){return this.a};Yb.prototype.toJSON=function(){return{name:this.a,keyPath:this.keyPath,type:this.type,unique:this.unique,multiEntry:this.multiEntry}};Yb.prototype.t=function(){var a=s(this.keyPath)?Wa(this.keyPath):this.keyPath;return new Yb(a,this.type,this.unique,this.multiEntry,this.a,this.c)};
function ac(a,b){return null!=a||null!=b?null!=a?null!=b?t(a)&&t(b)?Xa(a,b)?null:"expect: "+a+", but: "+b:bc(a,b)?null:"expect: "+a+", but: "+b:"keyPath: "+a+" no longer defined":"newly define "+b:null};function cc(a,b,c,d,e,f,g){this.c=a;if(!u(this.c))throw new G("store name must be a string");this.keyPath=r(b)?b:null;this.e=t(this.keyPath);if(null!==this.keyPath&&!u(this.keyPath)&&!this.e)throw new G("keyPath must be a string or array");this.b=c;var h;if(null!=d){h=Zb(d);if(!r(h))throw new G('type "'+d+'" for primary key in store "'+this.c+'" is invalid.');if(this.e)throw new G('composite key for store "'+this.c+'" must not specified type');}this.type=null!=h?h:this.b?"INTEGER":void 0;this.d=u(this.keyPath)?
this.keyPath.split("."):[];this.a=e||[];this.A=!!f;this.oa=!!g;this.g=s(this.keyPath)?this.keyPath.join(","):u(this.keyPath)?this.keyPath:"_ROWID_";ra(this.g);this.f=[]}m=cc.prototype;m.A=!1;m.oa=!1;m.toJSON=function(){for(var a=[],b=0;b<this.a.length;b++)a.push(this.a[b].toJSON());return{name:this.c,keyPath:this.keyPath,autoIncrement:this.b,type:this.type,indexes:a}};
function dc(a){var b=[],c=a.indexes||[];if(s(c))for(var d=0;d<c.length;d++){var e;e=c[d];e=new Yb(e.keyPath,e.type,e.unique,e.multiEntry,e.name,e.generator);r(e.keyPath)&&e.keyPath===a.keyPath||b.push(e)}return new cc(a.name,a.keyPath,a.autoIncrement,"undefined"===a.type||"null"===a.type?void 0:a.type,b,a.dispatchEvents,a.fixed)}m.t=function(){return dc(this.toJSON())};m.index=function(a){return this.a[a]||null};function ec(a,b){return Ua(a.a,function(a){return a.getName()==b})}
function fc(a,b){for(var c=0;c<a.a.length;c++)if(!ac(a.a[c].keyPath,b))return a.a[c];return null}function gc(a,b){return b===a.keyPath?!0:Ta(a.a,function(a){return a.getName()==b})}m.getName=function(){return this.c};function hc(a,b,c){if(b){if(!a.keyPath&&null!=c)return c;if(a.e){c=[];for(var d=0;d<a.keyPath.length;d++)c.push(wb(b,a.keyPath[d]));return c}if(a.keyPath)return ib(b,a.d)}}
function ic(a,b,c){for(var d=0;d<a.d.length;d++){var e=a.d[d];if(d==a.d.length-1){b[e]=c;break}r(b[e])||(b[e]={});b=b[e]}}
function jc(a,b){if(!b)return"missing store: "+a.c;if(a.c!=b.c)return"store name, expect: "+a.c+", but: "+b.c;var c=ac(a.keyPath,b.keyPath);if(c)return"keyPath, "+c;if(r(a.b)&&r(b.b)&&a.b!=b.b)return"autoIncrement, expect:  "+a.b+", but: "+b.b;if(a.a.length!=b.a.length)return"indexes length, expect:  "+a.a.length+", but: "+b.a.length;if(r(a.type)&&r(b.type)&&(t(a.type)?!Xa(a.type,b.type):a.type!=b.type))return"data type, expect:  "+a.type+", but: "+b.type;for(c=0;c<a.a.length;c++){var d=ec(b,a.a[c].getName()),
e;e=a.a[c];if(d)if(e.a!=d.a)e="name, expect: "+e.a+", but: "+d.a;else{var f=ac(e.keyPath,d.keyPath);e=f?"keyPath, "+f:null!=e.unique&&null!=d.unique&&e.unique!=d.unique?"unique, expect: "+e.unique+", but: "+d.unique:null!=e.multiEntry&&null!=d.multiEntry&&e.multiEntry!=d.multiEntry?"multiEntry, expect: "+e.multiEntry+", but: "+d.multiEntry:r(e.type)&&r(d.type)&&(t(e.type)?!Xa(e.type,d.type):e.type!=d.type)?"data type, expect: "+e.type+", but: "+d.type:""}else e="no index for "+e.a;if(0<e.length)return'index "'+
a.a[c].getName()+'" '+e}return""}function kc(a,b){if(b)for(var c=0;c<a.a.length;c++){var d=a.a[c],e=b;if(d.c){var f=d.c(e),g=typeof f;if("string"==g||"number"==g||f instanceof Date||s(f)){for(g=0;g<d.b.length-1;g++)y(e[d.b[g]])||(e[d.b[g]]={});e[d.b[d.b.length-1]]=f}}}}function S(a,b,c,d,e){for(var f=0;f<a.f.length;f++)d!==f&&a.f[f].call(e,b,c)};function lc(a){var b;try{b=T(a)}catch(c){b=""}return b?b.substr(0,70)+(70<b.length?"...":""):""}function T(a){return JSON.stringify(a,void 0,void 0)};function mc(a){this.a=a};function nc(a,b){this.name=a;this.a=b}nc.prototype.getName=function(){return this.name};nc.prototype.count=function(){return this.a.length};nc.prototype.index=function(a){return this.a[a]};function oc(a){if(!s(a.sources))throw new G("indexes require for full text search index "+a.name+", but "+a.sources+" of type "+typeof a.sources+" found.");var b=a.sources.map(function(a){return new mc(a.storeName)});return new nc(a.name,b)};function pc(a,b){var c,d,e=b;if(y(a)){d=a;c=d.version;for(var e=[],f=d.stores||[],g=0;g<f.length;g++){var h=dc(f[g]);e.push(h)}}else u(a)?c=0==a.length?void 0:parseFloat(a):x(a)&&(c=a);if(r(c)){if(!x(c)||0>c)throw new G("Invalid version: "+c+" ("+a+")");isNaN(c)&&(c=void 0)}if(r(b)&&(!s(b)||0<b.length&&!(b[0]instanceof cc)))throw new G("stores");this.version=c;this.b=!r(this.version);this.stores=e||[];c=[];if(d&&d.fullTextCatalogs)for(g=0;g<d.fullTextCatalogs.length;g++)e=oc(d.fullTextCatalogs[g]),
c[g]=e,U(this,e.getName())||(f=[new Yb("k","TEXT"),new Yb("v","TEXT")],e=new cc(e.getName(),"id",!1,void 0,f),this.stores.push(e));this.c=c}pc.prototype.toJSON=function(){var a=Sa(this.stores,function(a){return a.toJSON()}),b={};b.stores=a;r(this.version)&&(b.version=this.version);return b};pc.prototype.b=!1;pc.prototype.a=function(){return!1};function qc(a){return Sa(a.stores,function(a){return a.getName()})}pc.prototype.count=function(){return this.stores.length};
function U(a,b){return Ua(a.stores,function(a){return a.getName()==b})}function rc(a,b){return Ta(a.stores,function(a){return a.getName()==b})}
function sc(a,b){if(!b||a.stores.length!=b.stores.length)return"Number of store: "+a.stores.length+" vs "+b.stores.length;for(var c=0;c<a.stores.length;c++){var d=U(b,a.stores[c].getName());if(d){for(var e=d,f=a.stores[c],g=0;g<f.a.length;g++){var h=f.a[g];gc(e,h.getName())||"BLOB"!=h.type||(h=new Yb(h.keyPath,h.type,h.unique,h.multiEntry,h.getName()),e.a.push(h))}d=jc(a.stores[c],d);if(0<d.length)return'store: "'+a.stores[c].getName()+'" '+d}else return'missing object store "'+a.stores[c].getName()+
'"'}return""};function tc(a,b){pc.call(this,a,b)}A(tc,pc);tc.prototype.a=function(){return!0};function uc(a,b){a.stores.push(b)};function vc(a){Error.captureStackTrace?Error.captureStackTrace(this,vc):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.error.InternalError"}A(vc,Error);vc.prototype.name="ydn.InternalError";function wc(a){Error.captureStackTrace?Error.captureStackTrace(this,wc):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.error.ConstraintError"}A(wc,Error);wc.prototype.name="ydn.error.ConstraintError";
function xc(a){Error.captureStackTrace?Error.captureStackTrace(this,xc):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.error.InvalidOperationException"};function bc(a,b){var c;c=c||{};if(null!=a&&null!=b){if(t(a)&&t(b)){if(a.length!=b.length)return!1;for(var d=0;d<a.length;d++)if(-1==Ua(b,function(b){return bc(b,a[d])}))return!1;return!0}if(t(a))return 1==a.length&&bc(a[0],b);if(t(b))return 1==b.length&&bc(b[0],a);if(y(a)&&y(a)){for(var e in a)if(a.hasOwnProperty(e)&&!c[e]){var f=bc(a[e],b[e]);if(!f)return!1}for(e in b)if(b.hasOwnProperty(e)&&!c[e]&&(f=bc(a[e],b[e]),!f))return!1;return!0}return a===b}return!1};/*
 Copyright 2012 YDN Authors, Yathit. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License");.
*/
function V(a,b,c){c=c||{};this.m=c.mechanisms||yc;this.n=r(c.connectionTimeout)?c.connectionTimeout:18E5;this.a=null;this.e=[];this.T=!1;var d;if(b instanceof pc)d=b;else if(y(b)){c.autoSchema||!r(b.stores)?d=new tc(b):d=new pc(b);var e=b.stores?b.stores.length:0;for(c=0;c<e;c++)U(d,b.stores[c].name)}else d=new tc;this.b=d;for(c=0;c<this.b.count();c++);r(a)&&this.j(a);this.d=new E}
V.prototype.q=function(a){if(r(a)){var b=function(b){a(b.toJSON());a=void 0};if(this.a)zc(this.a,b);else{var c=this;this.L(function(a){zc(c.a,b,a)},null,H)}}return this.b?this.b.toJSON():null};function Ac(a,b){var c=b instanceof cc?b:dc(b),d=U(a.b,b.name);if(0==jc(c,d).length)(new E).k(!1);else if(a.b instanceof tc)uc(a.b,c),a.a?(a.a.close(),a.a=null,Bc(a)):(new E).k(!1);else throw new wc("");}V.prototype.j=function(a){if(this.a)throw new gb("Already connected with "+this.f);this.f=a;Bc(this)};
V.prototype.getName=function(){return this.f};var yc="indexeddb sqlite websql localstorage sessionstorage userdata memory".split(" ");m=V.prototype;m.W=function(){return null};
function Bc(a){function b(b,e){b?(a.ia=NaN,d.Ja=function(){},d.ma=function(){a.a=null},d.wa=function(){},setTimeout(function(){Cc(a,e);Dc(a)},10),c.k(e)):(setTimeout(function(){Cc(a,new Qb(a,e));if(a.e)for(var b;b=a.e.shift();)b.o&&b.o("error",e)},10),c.i(e))}for(var c=new E,d=null,e=a.m,f=0;f<e.length;f++){var g=e[f].toLowerCase();if(d=a.W(g)){d=a.W(g);break}}null===d?(e=new wc("No storage mechanism found."),b(!1,new Qb(a,e))):F(Ec(d,a.f,a.b),function(a){this.a=d;b(!0,new Ob("ready",this,parseFloat(d.l?
parseFloat(d.l.version):void 0),parseFloat(a),null))},function(a){b(!1,a)},a)}m.ca=function(){if(this.a)return"indexeddb"};m.U=function(a,b){this.d.ga(a,b)};function Cc(a,b){setTimeout(function(){a.b.b&&a.d.c||(b instanceof Pb?a.d.i(b.error):a.d.k())},4)}function Fc(a){return!!a.a&&!!a.a.l}m.close=function(){this.a&&(this.a.close(),this.a=null)};m.ia=NaN;function Dc(a){var b=a.e.shift();b&&a.L(b.R,b.Ca,b.mode,b.o);a.ia=ja()}m.T=!1;
m.L=function(a,b,c,d){var e=b;u(b)?e=[b]:null!=b||(e=null);if(this.a&&this.a.l&&!this.T){var f=this,g=r(c)?c:H;g==vb&&(this.T=!0);Gc(this.a,function(b){a(b);a=null},e,g,function(a,b){da(d)&&(d(a,b),d=void 0);g==vb&&(f.T=!1);Dc(f)})}else this.e.push({R:a,Ca:e,mode:c,o:d})};V.prototype.close=V.prototype.close;V.prototype.getType=V.prototype.ca;V.prototype.getName=V.prototype.getName;V.prototype.getSchema=V.prototype.q;V.prototype.onReady=V.prototype.U;V.prototype.setName=V.prototype.j;V.prototype.transaction=V.prototype.L;ka("ydn.db.version","1.0.2");ka("ydn.db.cmp",Ib);ka("ydn.db.deleteDatabase",function(a,b){for(var c,d=0;d<Jb.length;d++){var e=Jb[d](a,b);e&&(c=e)}return c||Hb("vc",null)});Ob.prototype.name=Ob.prototype.name;Ob.prototype.getVersion=Ob.prototype.Ka;
Ob.prototype.getOldVersion=Ob.prototype.va;Ob.prototype.getOldSchema=Ob.prototype.ua;Pb.prototype.getError=Pb.prototype.c;L.prototype.abort=L.prototype.abort;L.prototype.canAbort=L.prototype.sa;L.prototype.progress=L.prototype.za;L.prototype.promise=L.prototype.Ia;function Hc(a,b,c){Kb.call(this);this.B=c;this.F=c.getName();this.h=void 0;this.j=!1;this.ea=null;this.q=a;this.e=this.d=!1;this.m=this.c=this.b=void 0;this.f=function(){throw new hb;};this.g=function(){throw new hb;};this.n=function(){}}A(Hc,Kb);function Ic(a,b,c,d,e){if(r(b)){var f=a.B;b=s(b)?fc(f,b):ec(f,b);a.h=b.getName()}a.j=u(a.h);a.ea=c||null;a.d=!1;a.e=!1;a.N="prev"==d||"prevunique"==d;a.unique="nextunique"==d||"prevunique"==d;a.u=d;a.Z=e;a.b=void 0;a.c=void 0;a.m=void 0}m=Hc.prototype;
m.u="";m.ea=null;m.unique=!1;m.N=!1;m.Z=!0;function Jc(a,b,c,d){null==b&&(a.d=!0);a.b=b;a.c=c;a.m=d;a.d?(a.f(),Kc(a)):a.f(a.b)}function Kc(a){null!=a.c?a.c=Rb(a.c):a.c=void 0;null!=a.b?a.b=Rb(a.b):a.b=void 0;a.n(a.e,a.b,a.c)}m.open=function(a,b,c,d){this.q=a;this.d=this.e=!1;this.b=c;this.c=d;this.openCursor(this.b,this.c)};function Lc(a){a.e=!0;Kc(a)}function Mc(a){return a.j?a.c:a.b}function Nc(a){return a.Z?Mc(a):a.m}m.da=function(){};m.M=function(){};function Oc(){};function W(a,b,c,d,e,f,g){this.c=a;this.d=b;this.j=g;this.m=!!this.d;this.b=r(f)?f:!!u(this.d);a="next";d&&e?a="prevunique":d?a="prev":e&&(a="nextunique");this.f=a;this.a=Tb(c);this.e=Pc;this.n=NaN}A(W,Oc);W.prototype.b=!0;var Pc="init";W.prototype.t=function(){var a=new W(this.c,this.d,this.a,Qc(this),Rc(this),this.b,this.j);a.n=this.n;return a};W.prototype.unique=function(a){return new W(this.c,this.d,this.a,Qc(this),a,this.b,this.j)};
function Sc(a,b,c){a=new W(a.c,a.d,a.a,Qc(a),Rc(a),a.b,a.j);a.g=b;a.h=c;a.e="rest";return a}function Qc(a){return"prev"===a.f||"prevunique"===a.f}function Rc(a){return"nextunique"===a.f||"prevunique"===a.f}W.prototype.load=function(a){a=a[0];Ic(a,this.j||this.d,this.a,this.f,this.b);this.e="busy";var b=this;a.n=function(a,d,e){b.g=d;b.h=e;b.e=a?"rest":"done"};a.openCursor(this.g,this.h);return a};function Tc(a,b,c,d){b=b||Pc;"busy"!=a.e&&(a.g=c,a.h=d,a.e=b)}W.prototype.stores=function(){return[this.c]};function Uc(a){this.b=a||null;this.a=!1}function Vc(a,b){var c;a.a=Qc(b[0]);for(c=0;c<b.length;c++);return!1}Uc.prototype.c=function(){return[]};function Wc(a){Error.captureStackTrace?Error.captureStackTrace(this,Wc):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ConstraintError"}A(Wc,Error);Wc.prototype.name="ConstraintError";function Eb(a){Error.captureStackTrace?Error.captureStackTrace(this,Eb):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="InvalidStateError"}A(Eb,Error);
function Xc(a){Error.captureStackTrace?Error.captureStackTrace(this,Xc):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="InvalidAccessError"}A(Xc,Error);function Yc(a){Error.captureStackTrace?Error.captureStackTrace(this,Yc):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="NotFoundError"}A(Yc,Error);Yc.prototype.name="NotFoundError";
function Zc(a){Error.captureStackTrace?Error.captureStackTrace(this,Zc):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.db.TimeoutError"}A(Zc,Error);function $c(a,b){this.a=b};function ad(a){this.d=a;this.a=null;this.b=0}ad.prototype.r=null;function bd(a){return!!a.a&&!a.c}ad.prototype.o=null;function cd(a,b,c,d,e,f){this.h=a;this.F=b;this.a=this.d=0;this.B=d;this.q=e;this.f=c||dd;this.j=f||0}cd.prototype.type=function(){return this.h.ca()};cd.prototype.v=function(){return"B"+this.F+"T"+this.d};var dd="single";function ed(a){if(a)if(da(a.abort))a.abort();else if(da(a.executeSql))a.executeSql("ABORT",[],null,function(){return!0});else throw new fb;else throw new Eb("No active transaction");};function fd(a,b,c,d,e,f){cd.call(this,a,b,c,d,e,f);this.c=[];this.e=[];this.g=null;this.b=new ad(b);this.m=f||0;this.n=!1}A(fd,cd);
function gd(a,b,c){if("multi"==a.f)a:if(a=a.b,!a.r||!a.mode||c!=a.mode&&(a.mode!=I||c!=H)||b.length>a.r.length)b=!1;else{for(c=0;c<b.length;c++)if(-1==a.r.indexOf(b[c])){b=!1;break a}b=!0}else if("repeat"==a.f)a:if(a=a.b,a.r&&a.mode&&c==a.mode&&a.r.length==b.length){for(c=0;c<b.length;c++)if(-1==a.r.indexOf(b[c])){b=!1;break a}b=!0}else b=!1;else b="all"==a.f?!0:!1;return b}function hd(a){var b=0<a.c.length?a.c[0].r:null,c=0<a.c.length?a.c[0].mode:null;return null!=b&&null!=c?gd(a,b,c):!1}m=fd.prototype;
m.abort=function(){ed(this.g)};
m.C=function(a,b,c,d){var e=u(b)?[b]:b,f=r(c)?c:H,g=this;if(this.b.a||!Fc(this.h)&&this.n)this.c.push({R:a,r:b,mode:f,o:d});else{d&&this.e.push(d);if(this.m&&this.d>=this.m)throw new gb("Exceed maximum number of transactions of "+this.m);this.n=!0;this.h.L(function(c){var d=g.b;d.a=c;d.c=!1;d.r=b;d.mode=f;d.b++;d.o=null;T(b);a(g);for(a=null;hd(g);)c=g.c.shift(),c.o&&g.e.push(c.o),c.R()},e,f,function(a,b){var c=g.b;c.a&&(c.a=null,c.r=null,c.mode=null,da(c.o)&&c.o(a,b),c.o=null);for(c=0;c<g.e.length;c++)(0,g.e[c])(a,
b);g.e.length=0;(c=g.c.shift())&&g.C(c.R,c.r,c.mode,c.o);g.a=0})}};m.v=function(){var a=this.b;return"B"+a.d+"T"+a.b};m.request=function(a,b,c,d){function e(a,b){f.a=null;d&&d(a,b)}var f=new L(a);a=c||H;var g=this;bd(this.b)&&gd(this,b,a)?(b=this.b.a,this.a++,Db(f,b,this.v()+"R"+this.a),this.e.push(e)):g.C(function(){var a=g.b.a;g.a++;Db(f,a,g.v()+"R"+g.a)},b,a,e);return f};
m.w=function(a,b,c,d,e){d=d||H;var f=this,g;if(bd(f.b)&&gd(this,c,d)){var h=f.b.a;f.a++;g=f.v()+"R"+f.a;b(h,g,function(b,c){f.g=h;c?a.i(b):a.k(b);f.g=null});b=null}else f.C(function(){var c=f.b.a;f.a++;g=f.v()+"R"+f.a;b(c,g,function(b,d){f.g=c;d?a.i(b):a.k(b);f.g=null});b=null},c,d,e)};m.getName=function(){return this.h.getName()};function id(a,b){fd.call(this,a,b)}A(id,fd);id.prototype.request=function(a,b,c){var d,e,f,g=id.p.request.call(this,a,b,c,function(a,b){g.a=null;if(d)"complete"!=a&&(f=!0,e=b),d(e,f);else{var c=new Zc;N(g,c,!0)}});Fb(g,function(a,b,c){f=b;e=a;d=c});return g};
id.prototype.w=function(a,b,c,d,e){var f,g,h=new E;F(h,function(a){g=!1;f=a},function(a){g=!0;f=a});id.p.w.call(this,h,b,c,d,function(b,c){if("complete"!=b)a.i(c);else if(!0===g)a.i(f);else if(!1===g)a.k(f);else{var d=new Zc;a.i(d)}e&&(e(b,c),e=void 0)})};function jd(a,b,c){this.c=a;this.b=b;this.a=c;this.d=null}jd.prototype.e=function(){return this.a.d};jd.prototype.abort=function(){this.a.abort()};function X(a){if(!a.d){var b;b=a.c;var c=b.ca();if("indexeddb"==c)b=new kd(0,b.b);else throw new hb("No executor for "+c);a.d=b}return a.d};function Y(a,b,c){jd.call(this,a,b,c)}A(Y,jd);m=Y.prototype;
m.count=function(a,b,c,d){var e,f,g,h;if(null!=a)if(s(a)){if(r(c)||r(b))throw new G("too many arguments.");f=a;for(var k=0;k<f.length;k++)if(!rc(this.b,f[k]))throw new G('store name "'+f[k]+'" at '+k+" not found.");rb("countStores: "+T(f));e=this.a.request("d",f);O(e,function(){ld(X(this),e,f)},this)}else if(u(a)){k=U(this.b,a);if(!k)throw new G('store name "'+a+'" not found.');f=[a];if(u(b))g=b,y(c)?h=Tb(c):h=null;else if(y(b)||null==b)if(y(b))h=Tb(b);else{if(null!=b)throw new G("key range must be  an object but found "+
lc(b)+" of type "+typeof b);h=null}else throw new G('invalid second argument for count "'+lc(c)+'" of type '+typeof b);rb("countKeyRange: "+a+" "+(g?g:"")+T(h));e=this.a.request("d",f);S(k,e,arguments);O(e,function(){md(X(this),e,f[0],h,g)},this)}else throw new G("Invalid store name or store names.");else k=qc(this.b),e=this.a.request("d",k),Fb(e,function(a,b,c){if(b)c(a,!0);else{for(var d=b=0;d<a.length;d++)b+=a[d];c(b,!1)}},this),O(e,function(){ld(X(this),e,f)},this);return e};
m.get=function(a,b){var c=this,d;if(a instanceof Q){var e=a,f=e.a,g=U(this.b,f);if(!g){if(this.b.a()){if(Fc(this.c))return Hb("e",void 0);d=new L("e");this.c.U(function(){F(c.get(a,b),function(a){d.k(a)},function(a){d.i(a)})});return d}throw new G("Store: "+f+" not found.");}var h=e.b;d=this.a.request("ek",[f]);S(g,d,arguments,void 0,this);O(d,function(){nd(X(this),d,f,h)},this)}else if(u(a)&&r(b)){var k=a,g=U(this.b,k);if(!g){if(this.b.a()){if(Fc(this.c))return Hb("e",void 0);d=new L("e");this.c.U(function(){F(c.get(a,
b),function(a){d.k(a)},function(a){d.i(a)})});return d}throw new G('Store name "'+k+'" not found.');}var p=b;d=this.a.request("e",[k]);S(g,d,arguments,void 0,this);O(d,function(){nd(X(this),d,k,p)},this)}else throw new G("get require valid input arguments.");return d};
m.H=function(a,b,c,d,e,f,g){var h,k,p=null,n=!1,l=!1,v=a,C=U(this.b,v);if(this.b.a()&&!C)return Hb("g",[]);var w;if(u(b)){var D=b,p=Tb(c);if(x(d))h=d;else{if(r(d))throw new G("limit must be a number");h=100}if(x(e))k=e;else{if(r(e))throw new G("offset must be a number");k=0}if(r(f))if(ca(f))n=f;else throw new G("reverse must be a boolean");if(r(g))if(ca(g))l=g;else throw new G("unique must be a boolean");w=this.a.request("i",[v]);S(C,w,arguments);O(w,function(){od(X(this),w,2,v,D,p,h,k,n,l)},this)}else{y(b)?
p=Tb(b):p=null;if(x(c))h=c;else{if(r(c))throw new G("limit must be a number");h=100}if(x(d))k=d;else{if(r(d))throw new G("offset must be a number");k=0}if(r(e))if(ca(e))n=e;else throw new G("reverse must be a boolean");w=this.a.request("g",[v]);S(C,w,arguments);O(w,function(){od(X(this),w,2,v,null,p,h,k,n,!1)},this)}return w};
m.D=function(a,b,c,d,e,f,g){var h=this,k,p,n,l=!1,v=!1;if(u(a)){var C=a,w=U(this.b,C);if(!w){if(this.b.a()){if(Fc(this.c))return Hb("s",[]);k=new L("s");this.c.U(function(){F(h.D(a,b,c,d,e,f),function(a){k.k(a)},function(a){k.i(a)})});return k}throw new Yc(C);}if(s(b)){var D=b;k=this.a.request("v",[C]);S(w,k,arguments,void 0,this);O(k,function(){pd(X(this),k,C,D)},this)}else if(u(b)){var M=b,K=Tb(c);if(r(d))if(x(d))p=d;else throw new G("limit must be a number.");else p=100;if(r(e))if(x(e))n=e;else throw new G("offset must be a number.");
else n=0;if(ca(f))l=f;else if(r(f))throw new G("reverse must be a boolean, but "+f);if(r(g))if(ca(g))v=g;else throw new G("unique must be a boolean");k=this.a.request("u",[C]);S(w,k,arguments);O(k,function(){od(X(this),k,4,C,M,K,p,n,l,v)},this)}else{K=null;y(b)&&(K=Tb(b));if(r(c))if(x(c))p=c;else throw new G("limit must be a number, but "+c+" is "+typeof c);else p=100;if(r(d))if(x(d))n=d;else throw new G("offset must be a number, but "+d+" is "+typeof d);else n=0;if(r(e))if(ca(e))l=e;else throw new G("reverse must be a boolean, but "+
e+" is "+typeof e);k=this.a.request("s",[C]);S(w,k,arguments);O(k,function(){od(X(this),k,4,C,null,K,p,n,l,!1)},this)}}else if(s(a))if(a[0]instanceof Q){for(var w=[],P=a,aa=0;aa<P.length;aa++){var oa=P[aa].a;if(!rc(this.b,oa)){if(this.b.a())return w=[],w[P.length-1]=void 0,Hb("e",w);throw new G("Store: "+oa+" not found.");}0<=Ra(w,oa)||w.push(oa)}rb("listByKeys: "+T(w)+" "+P.length+" keys");k=this.a.request("w",w);O(k,function(){qd(X(this),k,P)},this)}else throw new G("first argumentmust be array of ydn.db.Key, but "+
a[0]+" of "+typeof a[0]+" found.");else throw new G("first argument "+a+" is invalid.");return k};
m.add=function(a,b,c){var d=u(a)?a:y(a)?a.name:void 0;if(!u(d))throw new G("store name "+d+" must be a string, but "+typeof d);var e=U(this.b,d);if(!e){if(!this.b.a())throw new G('store name "'+d+'" not found.');e=dc(y(a)?a:{name:d});Ac(this.c,e)}else if(this.b.a()&&y(a)&&(a=dc(a),a=jc(e,a)))throw new fb(a);var f;if(!e)throw new G('store name "'+d+'" not found.');if(u(e.keyPath)&&r(c))throw new G("key must not be provided while the store uses in-line key.");if(!e.keyPath&&!e.b&&!r(c))throw new G("out-of-line key must be provided.");
if(s(b)){for(a=0;a<b.length;a++)kc(e,b[a]);f=this.a.request("b",[d],I);O(f,function(){rd(X(this),f,!1,!1,d,b,c)},this);e.A&&f.s(function(){},this)}else if(y(b))hc(e,b,c),kc(e,b),f=this.a.request("a",[d],I),O(f,function(){rd(X(this),f,!1,!0,d,[b],[c])},this),e.A&&f.s(function(){},this);else throw new G("record must be an object or array list of objects, but "+b+" of type "+typeof b+" found.");return f};
function sd(a,b){var c=u(b)?b:y(b)?b.name:void 0;if(!u(c))throw new G("store name must be a string");var d=U(a.b,c);if(!d){if(!a.b.a())throw new Yc(c);d=dc(y(b)?b:{name:c});Ac(a.c,d)}else if(a.b.a()&&y(b)){var e=dc(b);if(e=jc(d,e))throw new fb(e);}if(!d)throw new Yc(c);return d}m.load=function(a,b,c){var d=c||",",e=sd(this,a).getName();a=this.a.request("i3",[e]);var f=this;this.a.w(a,function(a,c,k){td(X(f),a,k,e,b,d)},[e],I);return a};
m.put=function(a,b,c){var d,e=this;if(a instanceof Q){var f=a,g=f.a,h=U(this.b,g);if(!h)throw new G('store "'+g+'" not found.');if(h.keyPath){var k=hc(h,b);if(null!=k){if(0!=Ib(k,f.b))throw new G("Inline key must be "+f+" but "+k+" found.");}else ic(h,b,f.b);return this.put(g,b)}return this.put(g,b,f.b)}if(s(a)){for(var p=a,n=b,f=[],g=0,h=p.length;g<h;g++){k=p[g].a;-1==Ra(f,k)&&f.push(k);var l=U(this.b,k);if(!l)throw new G('store "'+k+'" not found.');l.keyPath&&ic(l,n[g],p[g].b)}rb("putByKeys: to "+
T(f)+" "+n.length+" objects");for(g=0;g<n.length;g++)kc(l,n[g]);d=this.a.request("l",f,I);S(l,d,arguments);O(d,function(){ud(X(e),d,n,p)},this)}else if(u(a)||y(a)){var l=sd(this,a),v=l.getName();if(l.keyPath&&r(c))throw new G("key must not be provided while the store uses in-line key.");if(!l.keyPath&&!l.b&&!r(c))throw new G("out-of-line key must be provided.");if(s(b)){for(var C=b,w=c,g=0;g<C.length;g++)kc(l,C[g]);d=this.a.request("k",[v],I);S(l,d,arguments);O(d,function(){rd(X(this),d,!0,!1,v,C,
w)},this);l.A&&d.s(function(){},this)}else if(y(b)){var D=b,M=c;if(r(q.Blob)&&D instanceof Blob&&l.oa&&!l.keyPath&&0==l.a.length&&qb)d=new L("j"),f=new FileReader,f.onload=function(a){var b=a.target.result,c=e.a.request("j",[v],I);S(l,c,[v,D,M]);O(c,function(){rd(X(e),c,!0,!0,v,[b],[M])},this);F(c,function(a){d.k(a)},function(a){d.i(a)})},f.onerror=function(a){d.i(a)},f.onabort=function(a){d.i(a)},f.readAsDataURL(D);else{kc(l,D);d=this.a.request("j",[v],I);var K=[v,D,M];S(l,d,K);O(d,function(){var a=
r(M)?[K[2]]:void 0;rd(X(e),d,!0,!0,v,[K[1]],a)},this)}l.A&&d.s(function(){},this)}else throw new G("put record value must be Object or array of Objects");}else throw new G("the first argument of put must be store name, store schema or array of keys.");return d};
m.clear=function(a,b){var c;if(u(a)){var d=U(this.b,a);if(!d)throw new G('store name "'+a+'" not found.');if(y(b)){var e=Tb(b);if(null===e)throw new G("clear method requires a valid non-null KeyRange object.");rb("clearByKeyRange: "+a+":"+T(e));c=this.a.request("c",[a],I);S(d,c,[a,e]);O(c,function(){vd(X(this),c,a,e)},this)}else{if(r(b))throw new G("clear method requires a valid KeyRange object as second argument, but found "+b+" of type "+typeof b);c=this.a.request("c",[a],I);O(c,function(){wd(X(this),
c,[a])},this)}}else if(!r(a)||s(a)&&u(a[0])){var f=a||qc(this.b);rb("clearByStores: "+T(f));c=this.a.request("c",f,I);O(c,function(){wd(X(this),c,f)},this)}else throw new G('first argument "'+a+'" is invalid.');return c};
m.V=function(a,b,c){var d;if(u(a)){var e=U(this.b,a);if(!e)throw new G('store name "'+a+'" not found.');if(r(c))if(u(b)){var f=ec(e,b);if(!f)throw new G("index: "+b+" not found in "+a);if(y(c)||null===c){var g=Tb(c);d=this.a.request("p",[a],I);O(d,function(){xd(X(this),d,a,f.getName(),g)},this)}else throw new G("key range "+c+' is invalid type "'+typeof c+'".');}else throw new G('index name "'+b+'" must be a string, but '+typeof b+" found.");else if(u(b)||x(b)||t(b)||b instanceof Date){d=this.a.request("m",
[a],I);var h=[a,b];S(e,d,h);O(d,function(){yd(X(this),d,a,h[1])},this);e.A&&d.s(function(){},this)}else if(y(b))g=Tb(b),rb("removeByKeyRange: "+a+":"+T(g)),d=this.a.request("n",[a],I),S(e,d,[a,g]),O(d,function(){zd(X(this),d,a,g)},this),e.A&&d.s(function(){},this);else throw new G('Invalid key or key range "'+b+'" of type '+typeof b);}else if(a instanceof Q){var k=a.a,e=U(this.b,k);d=this.a.request("m",[k],I);var p=[k,a.b];S(e,d,p);O(d,function(){yd(X(this),d,k,p[1])},this)}else if(s(a)){b=[];c=0;
for(e=a.length;c<e;c++){var n=a[c].a;-1==Ra(b,n)&&b.push(n)}if(1>b.length)throw new G('at least one valid key required in key list "'+lc(a)+'"');d=this.a.request("o",b,I);O(d,function(){Ad(X(this),d,a)},this)}else throw new G('first argument requires store name, key (ydn.db.Key) or list of keys (array) , but "'+lc(a)+'" ('+ba(a)+") found.");return d};function Bd(a,b,c){jd.call(this,a,b,c)}A(Bd,Y);m=Bd.prototype;m.get=function(a,b){if(a instanceof W){var c=a.c,d=U(this.b,c);if(!d)throw new G('store "'+c+'" not found.');var e=a.d;if(r(e)&&!gc(d,e))throw new G('index "'+e+'" not found in store "'+c+'".');var f=this.a.request("f",[c]);O(f,function(){Cd(this,5,f,a,1)},this);return f}return Bd.p.get.call(this,a,b)};
m.H=function(a,b,c,d,e,f,g){if(a instanceof W){var h=100;if(x(b)){if(h=b,1>h)throw new G("limit must be a positive value, but "+b);}else if(r(b))throw new G("limit must be a number,  but "+b);if(r(c))throw new G("offset must not be specified");var k=this.a.request("h",[a.c]);O(k,function(){a.m?Cd(this,1,k,a,h):Cd(this,2,k,a,h)},this);return k}return Bd.p.H.call(this,a,b,c,d,e,f,g)};
m.count=function(a,b,c,d){if(a instanceof W){if(r(b)||r(c))throw new G("too many arguments.");var e=this.a.request("d",[a.c]);O(e,function(){Cd(this,6,e,a)},this);return e}return Bd.p.count.call(this,a,b,c,d)};
m.D=function(a,b,c,d,e,f){if(a instanceof W){var g;if(x(b)){if(g=b,1>g)throw new G("limit must be a positive value, but "+g);}else if(r(b))throw new G("limit must be a number, but "+b);if(r(c))throw new G("offset must not be specified");var h=this.a.request("t",[a.c]);O(h,function(){a.b?Cd(this,2,h,a,g):Cd(this,4,h,a,g)},this);return h}return Bd.p.D.call(this,a,b,c,d,e,f)};
function Dd(a,b,c){var d,e=I||H,f=[];for(d=0;d<c.length;d++)for(var g=c[d].stores(),h=0;h<g.length;h++)0<=Ra(f,g[h])||f.push(g[h]);d=a.a.request("qa",f);a.a.w(d,function(d,e,f){function g(){for(var b=0,e=0;e<c.length;e++){var f=c[e],n=[Ed(X(a),d,f.c)],f=f.load(n);f.g=h;f.f=ia(C,b);aa[e]=f;M[b]=e;b++}D=c.length}function h(a){for(var b=0;b<aa.length;b++)Lc(aa[b]);Va(aa);f(a,!0)}function C(a,d){if(w)throw new vc;oa++;var e=oa===D,g=M[a],h=c[g],k=aa[g],g=Mc(k),k=Nc(k);K[a]=d;P[a]=h.m?h.b?g:k:h.b?d:k;
if(e){var p;b instanceof Uc?p=b.c(K,P):p=b(K,P);e=[];h=[];g=[];k=[];if(s(p))for(var l=0;l<p.length;l++)!0===p[l]?g[l]=1:!1===p[l]?k[l]=!0:h[l]=p[l];else if(null===p)e=[];else if(r(p))if(y(p))e=p.continuePrimary||[],h=p["continue"]||[],g=p.advance||[],k=p.restart||[];else throw new gb("scan callback output");else for(e=[],l=0;l<c.length;l++)r(M[l])&&(g[l]=1);for(l=oa=p=0;l<c.length;l++)null!=e[l]||r(h[l])||null!=k[l]||null!=g[l]||oa++;for(l=0;l<c.length;l++)if(null!=e[l]||r(h[l])||null!=k[l]||null!=
g[l]){var v=M[l];if(!r(v))throw new xc(l+" is not an iterator.");var v=c[v],C=aa[l];K[l]=void 0;P[l]=void 0;if(null!=k[l])v=C,v.d=!1,v.e=!1,v.openCursor(void 0,void 0);else if(r(h[l]))C.M(h[l]);else if(null!=e[l])C.da(e[l]);else if(null!=g[l])C.advance(1);else throw new vc(v+": has no action");p++}if(0==p){for(p=0;p<aa.length;p++)Lc(aa[p]);w=!0;Va(aa);f(void 0)}}}var w=!1,D,M=[],K=[],P=[],aa=[],oa=0;b instanceof Uc?Vc(b,c)||g():g()},f,e);return d}
m.open=function(a,b,c,d){c=c||H;var e=this,f=this.a.request("i5",b.stores(),c);O(f,function(c){for(var h=b.stores(),k=[],p=0;p<h.length;p++)k[p]=Ed(X(e),c,h[p]);var n=b.load(k);n.g=function(a){N(f,a,!0)};n.f=function(b){if(null!=b){var c=a.call(d,n);!0===c?(n.d=!1,n.e=!1,n.openCursor(void 0,void 0)):y(c)?!0===c.restart?(b=c["continue"],c=c.continuePrimary,n.d=!1,n.e=!1,n.openCursor(c,b)):null!=c["continue"]?n.M(c["continue"]):null!=c.continuePrimary?n.da(c.continuePrimary):(Lc(n),N(f,void 0)):null===
c?(Lc(n),N(f,void 0)):null!=c?n.M(c):n.advance(1)}else Lc(n),N(f,void 0)}},this);return f};m.map=function(a,b){for(var c=this,d=a.stores(),e,f=0;e=d[f];f++)if(!e)throw new G('Store "'+e+'" not found.');e=this.a.request("i4",d);this.a.w(e,function(d,e,f){e=a.stores();for(var p=[],n=0;n<e.length;n++)p[n]=Ed(X(c),d,e[n]);var l=a.load(p);l.g=function(a){f(a,!1)};l.f=function(c){if(null!=c){var d;a.m?a.b?d=c:d=Mc(l):a.b?d=c:d=Nc(l);b(d);l.advance(1)}else f(void 0),b=null}},d,H);return e};
function Fd(a,b,c,d){var e=c.c,f=c.d||null,g=d||100,h=a.a.request("u",[e]),k="done"==c.e||c.e==Pc?[]:[c.g,c.h];O(h,function(){od(X(this),h,b,e,f,c.a?c.a instanceof Vb?c.a:Vb.bound(c.a.lower,c.a.upper,c.a.lowerOpen,c.a.upperOpen):null,g,0,Qc(c),Rc(c),k)},a);h.s(function(){null!=k[0]?Tc(c,"rest",k[0],k[1]):Tc(c)});return h}
function Cd(a,b,c,d,e){var f=[],g=c.a;a=X(a);for(var h=[],k=d.stores(),p=0;p<k.length;p++)h[p]=Ed(a,g,k[p]);var n=d.load(h);n.g=function(a){Lc(n);N(c,a,!0)};var l=0,v=!1;n.f=function(a){v||(v=!0);null!=a?(l++,1==b?f.push(a):2==b?f.push(Mc(n)):3==b?f.push([a,Mc(n)]):6!=b&&f.push(Nc(n)),5==b?(Lc(n),N(c,f[0])):6==b||!r(e)||l<e?n.M():(Lc(n),N(c,f))):(Lc(n),N(c,5==b?f[0]:6==b?l:f))}};function Gd(a,b,c,d){this.d=a;this.a=Wa(c);this.b=d;this.c=[]}Gd.prototype.d=null;function Hd(a,b,c){if(a.d)c&&a.c.push(c),b(a.d);else throw new hb("tx committed on ParallelTxExecutor");};function Id(a,b,c,d,e,f){cd.call(this,a,b,c,d,e,f);this.c=this.b=null}A(Id,cd);m=Id.prototype;m.abort=function(){ed(this.c)};
m.pa=function(a,b){var c;if("multi"==this.f)a:if(c=this.b,!c.a||!c.b||b!=c.b&&(c.b!=I||b!=H)||a.length>c.a.length)c=!1;else{for(var d=0;d<a.length;d++)if(-1==c.a.indexOf(a[d])){c=!1;break a}c=!0}else if("repeat"==this.f)a:if(c=this.b,c.a&&c.b&&b==c.b&&c.a.length==a.length){for(d=0;d<a.length;d++)if(-1==c.a.indexOf(a[d])){c=!1;break a}c=!0}else c=!1;else c="all"==this.f?!0:!1;return c};
m.C=function(a,b,c,d){function e(c){h.d++;k=new Gd(c,0,b,g);T(b);h.b=k;Hd(h.b,a,d)}function f(a,b){if(k){for(var c=k,d=0;d<c.c.length;d++)c.c[d](a,b);c.c.length=0;c.d=null;c.a=null;c.c=null}h.a=0}this.B&&(b=this.B);this.q&&(c=this.q);var g=r(c)?c:H,h=this,k;if(this.b&&this.b.d&&this.pa(b,g))Hd(this.b,a,d);else{if(this.j&&this.d>=this.j)throw new gb("Exceed maximum number of transactions of "+this.j);this.h.L(e,b,g,f)}};
m.request=function(a,b,c,d){var e=new L(a),f=this;this.C(function(a){f.a++;Db(e,a,f.v()+"R"+f.a)},b,c||H,function(a,b){e.a=null;d&&d(a,b)});return e};m.w=function(a,b,c,d,e){var f=this,g;this.C(function(c){f.a++;g=f.v()+"R"+f.a;b(c,g,function(b,d){f.c=c;g=f.v()+"R"+f.a;d?a.i(b):a.k(b);f.c=null});b=null},c,d,e)};function Jd(a,b){Id.call(this,a,b,dd)}A(Jd,Id);Jd.prototype.pa=function(){return!1};Jd.prototype.request=function(a,b,c){var d,e,f,g=Jd.p.request.call(this,a,b,c,function(a,b){g.a=null;if(d)"complete"!=a&&(f=!0,e=b),d(e,f);else{var c=new Zc;N(g,c,!0)}});Fb(g,function(a,b,c){f=b;e=a;d=c});return g};
Jd.prototype.w=function(a,b,c,d,e){var f,g,h=new E;F(h,function(a){g=!1;f=a},function(a){g=!0;f=a});Jd.p.w.call(this,h,b,c,d,function(b,c){if("complete"!=b)a.i(c);else if(!0===g)a.i(f);else if(!1===g)a.k(f);else{var d=new Zc;a.i(d)}e&&(e(b,c),e=void 0)})};function Kd(a,b,c){V.call(this,a,b,c);this.G=0;a=!0;b=dd;c&&(r(c.isSerial)&&(a=!!c.isSerial),c.policy&&(b=c.policy));c=Ld(this,b,a);this.h=Ld(this,"atomic",!1);this.c=this.I(c,this.h)}A(Kd,V);m=Kd.prototype;m.G=0;m.qa=function(a,b,c,d,e,f){a=a||dd;var g;"readonly"==d?g=H:"readwrite"==d&&(g=I);a=Ld(this,a,b,c,g,e);return this.I(a,f?null:this.h)};m.I=function(a){return new jd(this,this.b,a)};
function Ld(a,b,c,d,e,f){if(c){if("multi"==b||"repeat"==b||"all"==b||b==dd)return new fd(a,a.G++,b,d,e,f);if("atomic"==b)return new id(a,a.G++);throw new G('Invalid requestType "'+b+'"');}if("multi"==b||"repeat"==b||"all"==b||b==dd)return new Id(a,a.G++,b,d,e,f);if("atomic"==b)return new Jd(a,a.G++);throw new G('Invalid requestType "'+b+'"');}
m.Ba=function(a,b,c){this.G++;b=b||qc(this.b);var d=H;if(c)if("readwrite"==c)d=I;else if("readonly"!=c)throw new G('Invalid transaction mode "'+c+'"');var e=Ld(this,"all",!1,b,d,1),f=this.I(e,this.h),g=new L("q");e.C(function(b){Db(g,b,e.v()+"R0");a(f)},b,d,function(a){g.a=null;N(g,e.d,"complete"!==a)});return g};m.La=function(){return this.c?this.c.a.d:NaN};function Z(a,b,c){Kd.call(this,a,b,c);a=this.b;for(b=0;b<a.c.length;b++){c=a.c[b];var d=U(a,c.getName());if(d){if(!gc(d,"k"))throw new G('full text index store "'+d.getName()+'" must have "keyword" index');if(!gc(d,"v"))throw new G('full text index store "'+d.getName()+'" must have "keyword" index');if("id"!=d.keyPath)throw new G('full text index store "'+d.getName()+'" must use "id" as key path.');}else throw new G('full text index store "'+c.getName()+'" required.');for(d=0;d<c.count();d++){var e=
c.index(d);if(!U(a,e.a))throw new G('full text source store "'+e.a+'" does not exist for full text index "'+c.getName()+'"');}}}A(Z,Kd);m=Z.prototype;m.I=function(a){return new Y(this,this.b,a)};m.add=function(a,b,c){return this.c.add(a,b,c)};m.count=function(a,b,c,d){return this.c.count(a,b,c,d)};m.get=function(a,b){return this.c.get(a,b)};m.H=function(a,b,c,d,e,f,g){return this.c.H(a,b,c,d,e,f,g)};m.D=function(a,b,c,d,e,f){return this.c.D(a,b,c,d,e,f)};
m.load=function(a,b,c){return this.c.load(a,b,c)};m.put=function(a,b,c){return this.c.put(a,b,c)};m.clear=function(a,b,c){return this.c.clear(a,b,c)};m.V=function(a,b,c){return this.c.V(a,b,c)};function Md(a,b,c){Z.call(this,a,b,c)}A(Md,Z);Md.prototype.I=function(a){return new Bd(this,this.b,a)};Md.prototype.open=function(a,b,c,d){return this.c.open(a,b,c,d)};Md.prototype.map=function(a,b){return this.c.map(a,b)};function Nd(a,b,c){Hc.call(this,a,0,c);this.a=null}A(Nd,Hc);m=Nd.prototype;m.Q=function(a){(a=a.target.result)?Jc(this,a.key,a.primaryKey,a.value):Jc(this)};
m.openCursor=function(a,b){function c(a,b,c){l.a=n;l.a.onsuccess=z(l.Q,l);Jc(l,a,l.j?b:void 0,c);n=null}var d=this.ea,e=this.q.objectStore(this.F),f=u(this.h)?e.index(this.h):null;if(r(a))var g=f?!r(b):!0,h=d?d.lower:void 0,k=d?d.upper:void 0,p=d?!!d.lowerOpen:!1,d=d?!!d.upperOpen:!1,d=Sb(this.N?new R(h,a,p,g):new R(a,k,g,d));var n;this.Z?f?n=null!=this.u?f.openKeyCursor(d,this.u):null!=d?f.openKeyCursor(d):f.openKeyCursor():n=null!=this.u?e.openCursor(d,this.u):null!=d?e.openCursor(d):e.openCursor():
f?n=null!=this.u?f.openCursor(d,this.u):null!=d?f.openCursor(d):f.openCursor():n=null!=this.u?e.openCursor(d,this.u):null!=d?e.openCursor(d):e.openCursor();var l=this;n.onerror=function(a){var b=n.error;a.preventDefault();l.g(b);Kc(l);l.d=!0};null!=a?n.onsuccess=function(d){if(d=d.target.result){var e=J.cmp(d.key,a),f=l.N?-1:1;if(e==f)c(d.key,d.primaryKey,d.value);else if(e==-f)d["continue"](a);else if(null!=b)if(J.cmp(d.primaryKey,b)==f)c(d.key,d.primaryKey,d.value);else d["continue"]();else d["continue"]()}else c()}:
(l.a=n,l.a.onsuccess=z(l.Q,l))};m.update=function(a){var b=this.a.result;if(b){var c=new E;a=b.update(a);a.onsuccess=function(a){c.k(a.target.result)};a.onerror=function(a){a.preventDefault();c.i(a)};return c}throw new Xc("cursor gone");};m.clear=function(){var a=this.a.result;if(a){var b=new E,a=a["delete"]();a.onsuccess=function(){b.k(1)};a.onerror=function(a){a.preventDefault();b.i(a)};return b}throw new Xc("cursor gone");};m.advance=function(a){var b=this.a.result;if(1==a)b["continue"]();else b.advance(a)};
m.da=function(a){var b,c=this.a.result,d=this;this.a.onsuccess=function(e){if(c=e.target.result)if(b=J.cmp(c.primaryKey,a),0==b||1==b&&!d.N||-1==b&&d.N)d.a.onsuccess=z(d.Q,d),Jc(d,c.key,d.j?c.primaryKey:void 0,c.value);else c["continue"]();else d.a.onsuccess=z(d.Q,d),Jc(d)};c["continue"]()};m.M=function(a){var b=this.a.result;if(null!=a)b["continue"](a);else b["continue"]()};function Od(a,b){this.a=b}A(Od,$c);function ld(a,b,c){function d(a){var g=b.a.objectStore(c[a]).count();g.onsuccess=function(g){e[a]=g.target.result;a++;a==c.length?N(b,e):d(a)};g.onerror=function(a){a.preventDefault();N(b,g.error,!0)}}var e=[];0==c.length?N(b,[]):d(0)}
function rd(a,b,c,d,e,f,g){function h(a){if(null==f[a])if(p++,p==f.length)N(b,k,n);else{var e=a+10;e<f.length&&h(e)}var w,e=f[a];w=g&&null!=g[a]?c?l.put(e,g[a]):l.add(e,g[a]):c?l.put(e):l.add(e);w.onsuccess=function(c){p++;k[a]=c.target.result;p==f.length?N(b,d?k[0]:k,n):(c=a+10,c<f.length&&h(c))};w.onerror=function(c){p++;var e=w.error;lc(f[a]);k[a]=e;n=!0;c.preventDefault();p==f.length?N(b,d?k[0]:k,n):(c=a+10,c<f.length&&h(c))}}var k=[],p=0,n=!1,l=b.a.objectStore(e);if(0<f.length)for(a=0;10>a&&
a<f.length;a++)h(a);else N(b,[])}function ud(a,b,c,d){function e(a){var p=d[a],n=b.a.objectStore(p.a),l;l=null===n.keyPath?n.put(c[a],p.b):n.put(c[a]);l.onsuccess=function(d){g++;f[a]=d.target.result;g==c.length?N(b,f,h):(d=a+10,d<c.length&&e(d))};l.onerror=function(d){g++;f[a]=l.error;h=!0;d.preventDefault();g==c.length?N(b,f,h):(d=a+10,d<c.length&&e(d))}}var f=[],g=0,h=!1;if(0<c.length)for(a=0;10>a&&a<c.length;a++)e(a);else N(b,f,h)}
function td(a,b,c,d,e,f){function g(){var a={},b=e.indexOf("\n",p),d=!1,D;-1==b?(d=!0,D=e.substring(p)):(D=e.substring(p,b),p=b+1);b=D.split(f);for(D=0;D<n.length;D++){var M=b[D];l[D]&&("TEXT"==l[D]?M=na(M):"INTEGER"==l[D]?M=parseInt(M,10):"NUMERIC"==l[D]&&(M=parseFloat(M)));a[n[D]]=M}var K=h.put(a);K.onsuccess=function(a){k.push(a.target.result);d?c(k):g()};K.onerror=function(a){a.preventDefault();c(K.error,!0)}}a=U(a.a,d);var h=b.objectStore(d),k=[],p=e.indexOf("\n"),n=e.substr(0,p).split(f),l=
[];for(b=0;b<n.length;b++)(d=ec(a,n[b]))?l[b]=d.type:n[b]==a.keyPath&&(l[b]=a.type);p++;g()}function yd(a,b,c,d){var e=b.a.objectStore(c).openCursor(Vb.only(d));e.onsuccess=function(a){if(a=a.target.result){var c=a["delete"]();c.onsuccess=function(){N(b,1)};c.onerror=function(){N(b,c.error,!0)}}else N(b,0)};e.onerror=function(a){a.preventDefault();N(b,e.error,!0)}}
function Ad(a,b,c){function d(a){a++;if(a>=c.length)0<h.length?N(b,h,!0):N(b,e);else{c[a].a!=f&&(f=c[a].a,g=b.a.objectStore(f));var p=g["delete"](c[a].b);p.onsuccess=function(){e++;d(a)};p.onerror=function(b){b.preventDefault();h[a]=p.error;d(a)}}}var e=0,f,g,h=[];d(-1)}
function zd(a,b,c,d){var e=b.a.objectStore(c),f=e.count(d);f.onsuccess=function(a){var c=a.target.result,f=e["delete"](d);f.onsuccess=function(){N(b,c)};f.onerror=function(){N(b,f.error,!0)}};f.onerror=function(a){a.preventDefault();N(b,f.error,!0)}}function vd(a,b,c,d){var e=b.a.objectStore(c)["delete"](d);e.onsuccess=function(){N(b,void 0)};e.onerror=function(a){a.preventDefault();N(b,e.error,!0)}}
function xd(a,b,c,d,e){var f=[],g=b.a.objectStore(c).index(d).openCursor(e),h=0;g.onsuccess=function(a){var c=a.target.result;if(c){var d=c["delete"]();d.onsuccess=function(){h++;c["continue"]()};d.onerror=function(a){f.push(d.error);a.preventDefault();c["continue"]()}}else 0<f.length?N(b,f,!0):N(b,h)};g.onerror=function(a){a.preventDefault();N(b,g.error,!0)}}
function wd(a,b,c){var d=c.length,e=0;for(a=0;a<d;a++){var f=b.a.objectStore(c[a]).clear();f.onsuccess=function(){e++;e==d&&N(b,e)};f.onerror=function(a){e++;a.preventDefault();e==d&&N(b,f.error,!0)}}}
function nd(a,b,c,d){var e=b.a.objectStore(c),f=e.get(d);f.onsuccess=function(a){var c=a.target.result;if(!e.keyPath&&0==e.indexNames.length&&qb&&u(c)&&0<=c.indexOf(";base64,")){'"'==c.charAt(0)&&'"'==c.charAt(c.length-1)&&(c=c.substr(1,c.length-2));c=c.split(";base64,");a=c[0].split(":")[1];for(var c=window.atob(c[1]),d=c.length,f=new Uint8Array(d),n=0;n<d;++n)f[n]=c.charCodeAt(n);N(b,new Blob([f.buffer],{type:a}))}else N(b,a.target.result)};f.onerror=function(a){a.preventDefault();N(b,f.error,!0)}}
function pd(a,b,c,d){function e(a){if(null==d[a])if(g++,f[a]=void 0,g==k)N(b,f);else{var c=a+10;c<k&&e(c)}var l;l=h.get(d[a]);l.onsuccess=function(c){g++;f[a]=c.target.result;g==k?N(b,f):(c=a+10,c<k&&e(c))};l.onerror=function(a){g++;a.preventDefault();N(b,l.error,!0)}}var f=[];f.length=d.length;var g=0,h=b.a.objectStore(c),k=d.length;if(0<k)for(a=0;10>a&&a<k;a++)e(a);else N(b,[])}
function qd(a,b,c){function d(a){var h=c[a],k=b.a.objectStore(h.a).get(h.b);k.onsuccess=function(h){f++;e[a]=h.target.result;f==c.length?N(b,e):(h=a+10,h<c.length&&d(h))};k.onerror=function(a){f++;a.preventDefault();N(b,k.error,!0)}}var e=[];e.length=c.length;var f=0;if(0<c.length)for(a=0;10>a&&a<c.length;a++)d(a);else N(b,[])}
function md(a,b,c,d,e){a=b.a.objectStore(c);d&&T(d);var f;null!=e?(e=a.index(e),f=null!=d?e.count(d):e.count()):f=null!=d?a.count(d):a.count();f.onsuccess=function(a){N(b,a.target.result)};f.onerror=function(a){a.preventDefault();N(b,f.error,!0)}}
function od(a,b,c,d,e,f,g,h,k,p,n){var l=[],v=b.a.objectStore(d);a=k?p?"prevunique":"prev":p?"nextunique":"next";d=Gb(b)+" "+c+" "+d+(e?":"+e:"")+(f?T(f):"");k&&(d+=" reverse");p&&(d+=" unique");if(n&&r(n[0])){p=e?!r(n[1]):!0;var C=n[0],w=f?f.lower:void 0,D=f?f.upper:void 0,M=f?!!f.lowerOpen:!1;f=f?!!f.upperOpen:!1;f=Sb(k?new R(w,C,M,p):new R(C,D,p,f));d+=" starting from "+T(n[0]);r(n[1])&&(d+=", "+T(n[1]))}var K;K=1==c||2==c||3==c?e?v.index(e).openKeyCursor(f,a):v.openCursor(f,a):e?v.index(e).openCursor(f,
a):v.openCursor(f,a);var P=!1;K.onsuccess=function(a){if(a=a.target.result){if(!P){if(0<h){P=!0;a.advance(h);return}if(n&&e&&r(n[0]))if(r(n[1])){var d=J.cmp(a.key,n[0]),f=k?-1:1;if(0==d){d=J.cmp(a.primaryKey,n[1]);if(0==d){P=!0;a["continue"]();return}if(d==f)P=!0;else{a["continue"]();return}}else P=!0}else P=!0;else P=!0}1==c?l.push(a.key):2==c?l.push(a.primaryKey):3==c?(f={},e&&(f[e]=a.key),v.keyPath?f[v.keyPath]=a.primaryKey:f._ROWID_=a.primaryKey,l.push(f)):4==c?l.push(a.value):l.push([a.key,a.primaryKey,
a.value]);if(l.length<g)a["continue"]();else n&&(n[0]=Rb(a.key),n[1]=Rb(a.primaryKey)),N(b,l)}else n&&(n[0]=void 0,n[1]=void 0),N(b,l)};K.onerror=function(a){a.preventDefault();N(b,K.error,!0)}};function kd(a,b){this.a=b}A(kd,Od);function Ed(a,b,c){a=U(a.a,c);return new Nd(b,0,a)};function Pd(a,b){this.l=null;this.J=b||NaN}
function Ec(a,b,c){function d(a,b){for(var d=0;d<c.stores.length;d++)Qd(a,b,c.stores[d]);for(var e=a.objectStoreNames,f=e.length,d=0;d<f;d++)rc(c,e[d])||a.deleteObjectStore(e[d])}function e(b,c){f.c||(r(c)?(a.l=null,f.i(c)):(a.l=b,a.l.onabort=function(){},a.l.onerror=function(){},a.l.onversionchange=function(b){if(a.l&&(a.l.onabort=null,a.l.onblocked=null,a.l.onerror=null,a.l.onversionchange=null,!b.defaultPrevented)){a.l.close();a.l=null;var c=Error();c.name=b.type;a.ma(c)}},f.k(parseFloat(g))))}
var f=new E,g=void 0,h=c.version,k;k=r(h)?J.open(b,h):J.open(b);k.onsuccess=function(f){var h=f.target.result;r(g)||(g=h.version);if(c.b)zc(a,function(a){if(c instanceof tc)for(var f=0;f<a.stores.length;f++)rc(c,a.stores[f].getName())||uc(c,a.stores[f].t());if(0<sc(c,a).length)if(a=x(h.version)?h.version+1:1,"IDBOpenDBRequest"in q){h.close();var g=J.open(b,a);g.onupgradeneeded=function(a){d(a.target.result,g.transaction)};g.onsuccess=function(a){e(a.target.result)};g.onerror=function(){e(null)}}else{var k=
h.setVersion(a+"");k.a=function(a){e(null,a)};k.onsuccess=function(){k.transaction.oncomplete=l;d(h,k.transaction)};var l=function(){var a=J.open(b);a.onsuccess=function(a){e(a.target.result)};a.onerror=function(){e(null)}};null!=k.transaction&&(k.transaction.oncomplete=l)}else e(h)},void 0,h);else if(c.version>h.version){var k=h.setVersion(c.version);k.a=function(a){e(null,a)};k.onsuccess=function(){d(h,k.transaction)}}else zc(a,function(a){a=sc(c,a);0<a.length?e(null,new wc("different schema: "+
a)):e(h)},void 0,h)};k.onupgradeneeded=function(a){a=a.target.result;g=NaN;d(a,k.transaction)};k.onerror=function(a){e(null,a)};k.onblocked=function(a){e(null,a)};x(a.J)&&!isNaN(a.J)&&setTimeout(function(){"done"!=k.readyState&&e(null,new Zc("connection timeout after "+a.J))},a.J);return f}m=Pd.prototype;m.J=18E4;m.ma=function(){};m.Ja=function(){};m.wa=function(){};m.l=null;
function zc(a,b,c,d){a=d||a.l;if(r(c)){if(null===c){if(0==a.objectStoreNames.length){b(new pc(a.version));return}throw new vc;}a=c.db}else{c=[];for(d=a.objectStoreNames.length-1;0<=d;d--)c[d]=a.objectStoreNames[d];if(0==c.length){b(new pc(a.version));return}c=a.transaction(c,H)}var e=a.objectStoreNames,f=[],g=e.length;for(d=0;d<g;d++){for(var h=c.objectStore(e[d]),k=[],p=0,n=h.indexNames.length;p<n;p++){var l=h.index(h.indexNames[p]);k[p]=new Yb(l.keyPath,void 0,l.unique,l.multiEntry,l.name)}f[d]=
new cc(h.name,h.keyPath,h.autoIncrement,void 0,k)}c=new pc(a.version,f);b(c)}
function Qd(a,b,c){function d(){var b={autoIncrement:!!c.b};null!=c.keyPath&&(b.keyPath=c.keyPath);return a.createObjectStore(c.getName(),b)}if(a.objectStoreNames.contains(c.getName())){b=b.objectStore(c.getName());ac(c.keyPath||"",b.keyPath||"")?(a.deleteObjectStore(c.getName()),b=d()):ca(b.autoIncrement)&&ca(c.b)&&b.autoIncrement!=c.b&&(a.deleteObjectStore(c.getName()),b=d());for(var e=b.indexNames,f=0;f<c.a.length;f++){var g=c.index(f);!e.contains(g.getName())&&g.c&&b.clear()}for(var h=0,k=0,p=
0,f=0;f<c.a.length;f++){var g=c.index(f),n=!1;if(e.contains(g.getName())){var l=b.index(g.getName()),v=null!=l.unique&&null!=g.unique&&l.unique!=g.unique,C=null!=l.multiEntry&&null!=g.multiEntry&&l.multiEntry!=g.multiEntry,l=null!=l.keyPath&&null!=g.keyPath&&!!ac(l.keyPath,g.keyPath);if(v||C||l)b.deleteIndex(g.getName()),n=!0,h--,p++}else"BLOB"!=g.type&&(n=!0);n&&(g.unique||g.multiEntry?(n={unique:g.unique,multiEntry:g.multiEntry},b.createIndex(g.getName(),g.keyPath,n)):b.createIndex(g.getName(),
g.keyPath),h++)}for(f=0;f<e.length;f++)gc(c,e[f])||(b.deleteIndex(e[f]),k++)}else for(b=d(),f=0;f<c.a.length;f++)g=c.index(f),"BLOB"!=g.type&&(g.unique||g.multiEntry?(n={unique:g.unique,multiEntry:g.multiEntry},b.createIndex(g.getName(),g.keyPath,n)):b.createIndex(g.getName(),g.keyPath))}
function Gc(a,b,c,d,e){a=a.l;if(!c){c=[];for(var f=a.objectStoreNames.length-1;0<=f;f--)c[f]=a.objectStoreNames[f]}0==c.length?b(null):(c=a.transaction(c,d),c.oncomplete=function(a){e("complete",a)},c.onabort=function(a){e("abort",a)},b(c),b=null)}m.close=function(){this.l.close()};
Jb.push(function(a,b){if(!J||b&&"indexeddb"!=b)return null;var c=J.deleteDatabase(a),d=new L("vc");c.onblocked=function(a){for(var b=0;b<d.f.length;b++)d.f[b][0].call(d.f[b][1],a)};c.onerror=function(a){d.i(a)};c.onsuccess=function(a){d.k(a)};return d});/*
 Copyright 2012 YDN Authors, Yathit. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License");.
*/
Kd.prototype.W=function(a){return"indexeddb"==a&&J?new Pd(0,this.n):null};/*
 Copyright 2012 YDN Authors, Yathit. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License");.
*/
Kd.prototype.branch=Kd.prototype.qa;Kd.prototype.getTxNo=Kd.prototype.La;jd.prototype.getTxNo=jd.prototype.e;Kd.prototype.run=Kd.prototype.Ba;Z.prototype.branch=Z.prototype.qa;Z.prototype.add=Z.prototype.add;Z.prototype.get=Z.prototype.get;Z.prototype.keys=Z.prototype.H;Z.prototype.values=Z.prototype.D;Z.prototype.put=Z.prototype.put;Z.prototype.clear=Z.prototype.clear;Z.prototype.remove=Z.prototype.V;Z.prototype.count=Z.prototype.count;Y.prototype.add=Y.prototype.add;Y.prototype.get=Y.prototype.get;Y.prototype.keys=Y.prototype.H;Y.prototype.values=Y.prototype.D;Y.prototype.put=Y.prototype.put;Y.prototype.clear=Y.prototype.clear;
Y.prototype.remove=Y.prototype.V;Y.prototype.count=Y.prototype.count;ka("ydn.db.Key",Q);Q.prototype.id=Q.prototype.ta;Q.prototype.parent=Q.prototype.Da;Q.prototype.storeName=Q.prototype.Ea;ka("ydn.db.KeyRange",R);R.upperBound=R.upperBound;R.lowerBound=R.lowerBound;R.bound=R.bound;R.only=R.only;R.starts=Ub;Nb.prototype.store_name=Nb.prototype.b;Nb.prototype.getStoreName=Nb.prototype.a;function Rd(a,b,c){Z.call(this,a,b,c)}A(Rd,Md);ka("ydn.db.Storage",Rd);function Sd(a,b,c){this.db=a;this.b=b;this.type=c||0;this.c=null};function Td(a){Uc.call(this,a)}A(Td,Uc);
Td.prototype.c=function(a,b){var c=[],d=b[0];if(null==d)return[];for(var e=!0,f=!1,g=d,h=[],k=1;k<a.length;k++)if(null!=b[k]){var p=Ib(d,b[k]);h[k]=p;this.a?-1==p?e=!1:1==p&&(e=!1,f=!0,-1==Ib(b[k],g)&&(g=b[k])):1==p?e=!1:-1==p&&(e=!1,f=!0,1==Ib(b[k],g)&&(g=b[k]))}else e=!1,f=!0;if(e)for(f=0;f<a.length;f++)null!=b[f]&&(c[f]=!0);else if(f)for(f=0;f<a.length;f++)null!=b[f]&&(this.a?-1==Ib(g,b[f])&&(c[f]=g):1==Ib(g,b[f])&&(c[f]=g));else for(k=this.a?-1:1,f=1;f<a.length;f++)h[f]===k&&(c[f]=d);return e?
(this.b&&this.b.push(g),c):{continuePrimary:c}};function Ud(a){Uc.call(this,a)}A(Ud,Uc);
Ud.prototype.c=function(a,b){function c(a,b){var c=a.slice(0,a.length-1);c.push(b);return c}function d(a){return a[a.length-1]}var e=[];if(0==a.length||null==a[0]||null==a[0])return[];for(var f=!0,g=0,h=d(a[g]),k=[],p=1;p<a.length;p++)if(null!=a[p]){var n=d(a[p]),l=Ib(h,n);k[p]=l;this.a?-1==l?f=!1:1==l&&(f=!1,h=n,g=1):1==l?f=!1:-1==l&&(f=!1,h=n,g=1)}else return[];p=this.a?-1:1;if(f){for(f=0;f<a.length;f++)null!=a[f]&&(e[f]=!0);this.b&&this.b.push(b[0]);return e}if(0==g)for(f=1;f<a.length;f++)k[f]==
p&&(e[f]=c(a[f],h));else for(f=0;f<a.length;f++)f!=g&&null!=a[f]&&Ib(h,d(a[f]))===p&&(e[f]=c(a[f],h));return{"continue":e}};function Vd(a,b,c,d){this.c=a;this.a=b||null;this.f=!!c;this.e=!!d;this.b=[];this.d=[]}function Wd(a,b){if((0!=a.b.length||0!=a.d.length)&&Xd(a)&&!Yd(a))throw new Wc('Require index "'+a.b.concat(a.d).join(", ")+'" not found in store "'+a.c.getName()+'"');var c=new W(a.c.getName(),Zd(a),a.a,a.f,a.e,!!b);c.n=a.b.length;return c}Vd.prototype.t=function(){var a=new Vd(this.c,this.a,this.f,this.e);a.d=this.d.slice();a.b=this.b.slice();return a};
function Yd(a){var b=a.b.concat(a.d),c=fc(a.c,b);return c||b[b.length-1]==a.c.keyPath&&(c=fc(a.c,b.slice(0,b.length-1)))?c:null}function Zd(a){return(a=Yd(a))?a.getName():void 0}Vd.prototype.unique=function(a){var b=this.t();b.e=!!a;return b};function Xd(a){return 0<a.b.length?!0:1==a.d.length?a.d[0]!=a.c.keyPath:1<a.d.length?!0:!1}
Vd.prototype.ba=function(a,b,c,d,e){c=Xb(b,c,d,e);if(0<this.b.length)if(this.a)if(null!=this.a.lower&&null!=this.a.upper&&0==Ib(this.a.lower,this.a.upper))a=s(this.a.lower)?this.a.lower.slice().push(b):[this.a.lower,b],d=null!=d?d:"\uffff",c=s(this.a.upper)?this.a.upper.slice().push(d):[this.a.upper,d],this.a=Xb(b,a,d,c);else if(1==this.b.length&&this.b[0]==a||s(a)&&Xa(this.b,a))this.a=Wb(this.a,c);else return"cannot use where clause with existing filter";else return"cannot use where clause with existing filter";
else this.b=s(a)?a:[a],this.a=this.a?Wb(this.a,c):c;return null};function $d(a,b,c,d){Sd.call(this,a,b,c);this.a=d}A($d,Sd);$d.prototype.open=function(){var a={push:function(){}},a=ae(this)?new Ud(a):new Td(a);return Dd(this.db,a,be(this))};function be(a){for(var b=[],c=0;c<a.a.length;c++)b[c]=Wd(a.a[c]);return b}function ae(a){for(var b=0;b<a.a.length;b++)if(0<a.a[b].b.length)return!0;return!1}$d.prototype.Y=function(){return this.a.slice()};function $(a,b,c,d){Sd.call(this,a,b,c);this.a=d}A($,Sd);m=$.prototype;m.Fa=function(){return new $(this.db,this.b,this.type,this.a.t())};m.Ha=function(){var a=this.a,b=a.t();b.f=!a.f;return new $(this.db,this.b,this.type,b)};m.unique=function(a){if(!ca(a))throw new G("unique value must be a boolean, but "+typeof a+" found");a=this.a.unique(a);return new $(this.db,this.b,this.type,a)};
m.xa=function(a){var b=u(a)?[a]:a;a=this.a.t();for(var c=b.length-1;0<=c;c--)if(b[c]==a.b[a.b.length-1])b=b.slice(0,c);else break;a.d=b;return new $(this.db,this.b,this.type,a)};
m.ba=function(a,b,c,d,e){if(Zd(this.a)&&Zd(this.a)!=a){var f=Xb(b,c,d,e),f=new Vd(U(this.b,this.a.c.getName()),f,this.a.f,this.a.e),f=(new $(this.db,this.b,this.type,f)).Y().concat(this.Y());return new $d(this.db,this.b,this.type,f)}if(!Zd(this.a)&&!gc(U(this.b,this.a.c.getName()),a))throw new G('index "'+a+'" not exists in '+this.a.c.getName());f=this.a.t();if(a=f.ba(a,b,c,d,e))throw new G(a);return new $(this.db,this.b,this.type,f)};
m.Ga=function(a){a=a||100;var b=4,c=ce(this);this.c&&this.c[0]&&(c=Sc(c,this.c[0],this.c[1]));if(2==this.type||3==this.type||1==this.type)b=this.type;a=Fd(this.db,b,c,a);a.s(function(){"rest"==c.e&&(this.c=[c.g,c.h])},this);return a};m.Y=function(){return[this.a.t()]};function ce(a){return Wd(a.a,!(2==a.type||3==a.type||1==a.type))}
m.ya=function(a,b){var c=ce(this);c.b&&(c=new W(c.c,c.d,c.a,Qc(c),Rc(c),!1,c.j));var d=this.db.open(function(c){var f=Nc(c);if(u(a))xb(f,a,b);else if(s(a))for(var g=0;g<a.length;g++)xb(f,a[g],b[g]);else if(y(a))for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);c=c.update(f);d.s(z(c.Aa,c))},c,I,this);return d};m.open=function(a,b){return this.db.open(a,ce(this),I,b)};
m.count=function(){return Xd(this.a)?this.a.e?this.db.count(Wd(this.a)):this.db.count(this.a.c.getName(),Zd(this.a),this.a.a):this.db.count(this.a.c.getName(),this.a.a)};m.clear=function(){return Xd(this.a)?this.db.clear(this.a.c.getName(),Zd(this.a),this.a.a):this.db.clear(this.a.c.getName(),this.a.a)};
Md.prototype.g=function(a,b,c,d,e){if(!rc(this.b,a))throw new G('Store "'+a+'" not found.');var f=null;if(r(b)){if(!r(c))throw new G("boundary value must be defined.");f=Xb(b,c,d,e)}else if(r(d))throw new G("second boundary must not be defined.");a=new Vd(U(this.b,a),f);return new $(this.c,this.b,null,a)};
Bd.prototype.g=function(a,b,c,d,e){if(!rc(this.b,a))throw new G('Store "'+a+'" not found.');var f=null;if(r(b)){if(!r(c))throw new G("boundary value must be defined.");f=Xb(b,c,d,e)}else if(r(d))throw new G("second boundary must not be defined.");a=new Vd(U(this.b,a),f);return new $(this,this.b,null,a)};$.prototype.copy=$.prototype.Fa;$.prototype.count=$.prototype.count;$.prototype.list=$.prototype.Ga;$.prototype.order=$.prototype.xa;$.prototype.patch=$.prototype.ya;$.prototype.reverse=$.prototype.Ha;$.prototype.unique=$.prototype.unique;$.prototype.where=$.prototype.ba;Md.prototype.from=Md.prototype.g;Bd.prototype.from=Bd.prototype.g; 

//# sourceMappingURL=ydn.db-i-core-qry.js.map
return ydn;}, (this || {}));
            
